version: '3'

services:
    app:
        container_name: simulator_outstation_dnp3_dynamic
        hostname: simulator_outstation_dnp3_dynamic
        image: simulator_outstation_dnp3_dynamic
        environment:
            - SPRING_PROFILES_ACTIVE
        build:
            context: .
            dockerfile: DOCKERFILE
        #        networks:
        #            app-tier:
        #                ipv4_address: 10.0.11.139
        volumes:
            - /home/docker-container-logs/simulator_outstation_dnp3_dynamic:/app/logs
        ports:
            - "47770:20000"
            - "47771:47771"
        restart: always

networks:
    app-tier:
        external: true
