apiVersion: apps/v1
kind: Deployment
metadata:
    name: simulator-outstation-dnp3-dynamic
    namespace: simulator-dnp3
spec:
    replicas: 1
    selector:
        matchLabels:
            app: simulator-outstation-dnp3-dynamic
    template:
        metadata:
            labels:
                app: simulator-outstation-dnp3-dynamic
        spec:
            imagePullSecrets:
                -   name: harbor-secret
            containers:
                -   name: simulator-outstation-dnp3-dynamic
                    image: 1.2.3.4/scada/simulator-outstation-dnp3-dynamic:latest
                    ports:
                        -   containerPort: 20000
                        -   containerPort: 47771
                    env:
                        -   name: TZ
                            value: Asia/Jakarta

---
apiVersion: v1
kind: Service
metadata:
    name: simulator-outstation-dnp3-dynamic-service
    namespace: simulator-dnp3
spec:
    selector:
        app: simulator-outstation-dnp3-dynamic
    type: NodePort
    ports:
        -   name: dnp3-port-20000
            protocol: TCP
            port: 20000
            targetPort: 20000
            nodePort: 30770
        -   name: dnp3-port-47771
            protocol: TCP
            port: 47771
            targetPort: 47771
            nodePort: 30771
